"""Update model relationships and types

Revision ID: 152406f7d045
Revises: 385bd907fa7b
Create Date: 2025-01-05 10:11:00.956139+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152406f7d045'
down_revision: Union[str, None] = '385bd907fa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_password_reset', 'users', ['password_reset_token', 'password_reset_expires'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('ix_users_verification', 'users', ['verification_token', 'is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verification', table_name='users')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index('ix_users_password_reset', table_name='users')
    # ### end Alembic commands ### 