"""remove_status_from_documents

Revision ID: f889a7128341
Revises: cc17b40fda28
Create Date: 2025-01-11 08:42:08.233883+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f889a7128341'
down_revision: Union[str, None] = 'cc17b40fda28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_status_type', table_name='documents')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=10), nullable=False))
    op.create_index('ix_documents_status_type', 'documents', ['status', 'type'], unique=False)
    # ### end Alembic commands ### 