"""update_analysis_models_and_relationships

Revision ID: 556c5aecc119
Revises: ef408e52d553
Create Date: 2025-02-22 18:12:59.126623+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556c5aecc119'
down_revision: Union[str, None] = 'ef408e52d553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 