"""update_analysis_models_and_relationships

Revision ID: 556c5aecc119
Revises: ef408e52d553
Create Date: 2025-02-22 18:12:59.126623+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556c5aecc119'
down_revision: Union[str, None] = 'ef408e52d553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create indexes for analysis_runs table if they don't exist
    op.create_index('ix_analysis_runs_document_id', 'analysis_runs', ['document_id'], unique=False, if_not_exists=True)
    op.create_index('ix_analysis_runs_analysis_definition_id', 'analysis_runs', ['analysis_definition_id'], unique=False, if_not_exists=True)
    op.create_index('ix_analysis_runs_status', 'analysis_runs', ['status'], unique=False, if_not_exists=True)
    
    # Create indexes for step_execution_results table if they don't exist
    op.create_index('ix_step_execution_results_analysis_run_id', 'step_execution_results', ['analysis_run_id'], unique=False, if_not_exists=True)
    op.create_index('ix_step_execution_results_step_definition_id', 'step_execution_results', ['step_definition_id'], unique=False, if_not_exists=True)
    op.create_index('ix_step_execution_results_status', 'step_execution_results', ['status'], unique=False, if_not_exists=True)

    # Ensure foreign key constraints are properly set
    with op.batch_alter_table('analysis_runs') as batch_op:
        batch_op.create_foreign_key(
            'fk_analysis_runs_document_id_documents',
            'documents',
            ['document_id'],
            ['id'],
            ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_analysis_runs_analysis_definition_id_analysis_definitions',
            'analysis_definitions',
            ['analysis_definition_id'],
            ['id'],
            ondelete='CASCADE'
        )

    with op.batch_alter_table('step_execution_results') as batch_op:
        batch_op.create_foreign_key(
            'fk_step_execution_results_analysis_run_id_analysis_runs',
            'analysis_runs',
            ['analysis_run_id'],
            ['id'],
            ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_step_execution_results_step_definition_id_step_definitions',
            'step_definitions',
            ['step_definition_id'],
            ['id'],
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints
    with op.batch_alter_table('step_execution_results') as batch_op:
        batch_op.drop_constraint('fk_step_execution_results_analysis_run_id_analysis_runs', type_='foreignkey')
        batch_op.drop_constraint('fk_step_execution_results_step_definition_id_step_definitions', type_='foreignkey')

    with op.batch_alter_table('analysis_runs') as batch_op:
        batch_op.drop_constraint('fk_analysis_runs_document_id_documents', type_='foreignkey')
        batch_op.drop_constraint('fk_analysis_runs_analysis_definition_id_analysis_definitions', type_='foreignkey')

    # Drop indexes
    op.drop_index('ix_step_execution_results_status', table_name='step_execution_results')
    op.drop_index('ix_step_execution_results_step_definition_id', table_name='step_execution_results')
    op.drop_index('ix_step_execution_results_analysis_run_id', table_name='step_execution_results')
    
    op.drop_index('ix_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_analysis_definition_id', table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_document_id', table_name='analysis_runs')
    # ### end Alembic commands ### 