"""update analysis execution models

Revision ID: 1c284fc4cd66
Revises: 2399cd3a4b68
Create Date: 2025-02-28 22:10:04.232284+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c284fc4cd66'
down_revision: Union[str, None] = '2399cd3a4b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle analysis_runs table changes
    with op.batch_alter_table('analysis_runs', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('analysis_code', sa.String(length=100), nullable=False))
        batch_op.drop_column('analysis_definition_id')

    # Handle documents table changes
    with op.batch_alter_table('documents', recreate='always') as batch_op:
        batch_op.alter_column('type',
                    existing_type=sa.VARCHAR(length=5),
                    type_=sa.Enum('PDF', 'DOCX', 'XLSX', 'IMAGE', 'UNKNOWN', name='documenttype'),
                    existing_nullable=False)

    # Handle step_execution_results table changes
    with op.batch_alter_table('step_execution_results', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('step_code', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('algorithm_code', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.drop_column('step_definition_id')
        batch_op.drop_column('algorithm_definition_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle step_execution_results table changes
    with op.batch_alter_table('step_execution_results', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('algorithm_definition_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('step_definition_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(None,
                                  'algorithm_definitions', ['algorithm_definition_id'], ['id'])
        batch_op.create_foreign_key(None,
                                  'step_definitions', ['step_definition_id'], ['id'])
        batch_op.drop_column('retry_count')
        batch_op.drop_column('algorithm_code')
        batch_op.drop_column('step_code')

    # Handle documents table changes
    with op.batch_alter_table('documents', recreate='always') as batch_op:
        batch_op.alter_column('type',
                    existing_type=sa.Enum('PDF', 'DOCX', 'XLSX', 'IMAGE', 'UNKNOWN', name='documenttype'),
                    type_=sa.VARCHAR(length=5),
                    existing_nullable=False)

    # Handle analysis_runs table changes
    with op.batch_alter_table('analysis_runs', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('analysis_definition_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(None,
                                  'analysis_definitions', ['analysis_definition_id'], ['id'])
        batch_op.drop_column('analysis_code')
    # ### end Alembic commands ### 