"""Add document and analysis models

Revision ID: 385bd907fa7b
Revises: 63ff594fb831
Create Date: 2025-01-05 10:02:29.018712+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385bd907fa7b'
down_revision: Union[str, None] = '63ff594fb831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PDF', 'DOCX', 'XLSX', 'IMAGE', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index('ix_documents_name', 'documents', ['name'], unique=False)
    op.create_index('ix_documents_status_type', 'documents', ['status', 'type'], unique=False)
    op.create_index('ix_documents_user_id_uploaded_at', 'documents', ['user_id', sa.text('uploaded_at DESC')], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TABLE_DETECTION', 'TEXT_EXTRACTION', 'TEXT_SUMMARIZATION', 'TEMPLATE_CONVERSION', name='analysistype'), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_results_created_at', 'analysis_results', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_analysis_results_document_id_type', 'analysis_results', ['document_id', 'type'], unique=False)
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_index('ix_analysis_results_type', 'analysis_results', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_results_type', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_index('ix_analysis_results_document_id_type', table_name='analysis_results')
    op.drop_index('ix_analysis_results_created_at', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_documents_user_id_uploaded_at', table_name='documents')
    op.drop_index('ix_documents_status_type', table_name='documents')
    op.drop_index('ix_documents_name', table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ### 