"""add_document_archival_fields

Revision ID: 9fc50cbda640
Revises: f889a7128341
Create Date: 2025-01-11 09:44:30.042057+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc50cbda640'
down_revision: Union[str, None] = 'f889a7128341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('archived_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('previous_version_id', sa.String(), nullable=True))
    op.alter_column('documents', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_documents_name', table_name='documents')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'documents', ['previous_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_documents_name', 'documents', ['name'], unique=False)
    op.alter_column('documents', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('documents', 'previous_version_id')
    op.drop_column('documents', 'archived_url')
    op.drop_column('documents', 'archived_at')
    # ### end Alembic commands ### 