"""add document status field and index

Revision ID: cc17b40fda28
Revises: 0a4de00df048
Create Date: 2025-01-11 00:59:17.699015+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc17b40fda28'
down_revision: Union[str, None] = '0a4de00df048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False))
    op.create_index('ix_documents_status_type', 'documents', ['status', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_status_type', table_name='documents')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ### 